### ISSUE TITLE
Is this project supported? Are you looking for supporters?

### ISSUE THREAD

**Issue by njvack** [redcap-tools/PyCap#127]
At the start of the README, we have:

"I am no longer actively developing this code base. Please continue to submit bugs and I'll do my best to tackle them."

There _are_ still commits happening, at least periodically, and there have been a couple of releases this year. Is that "no more active development" statement still true?

PyCap is useful enough to  our group that we would like to see its continued development, along with releases to PyPI (maybe condaforge, too?) and such. If you're looking for contributors, I suspect I (and others at my center) might be able to do some of that.

And! Thank you for making such a useful library. It sure beats screwing around with requests to get REDCap data into a dataframe.

**Comment by pwildenhain** [comment]
Thanks for pointing this out -- if you check out #109 you'll see that I was in a similar predicament back in January. @sburns (who I agree has done great work with this project 💯) granted me access to the repo. 

Since then, I've been merging PRs for new functionality/endpoints, bugfixes, etc. and then releasing to PyPI every so often.

I could see removing that notice from the README.md -- maybe swapping it out for a message that let's people know this project is purely _community supported_ and people should submit new features if they would like to see them on PyPI.

More hands on deck 🚢 is **always** welcome -- feel free to submit a PR anytime ✔️

**Comment by njvack** [comment]
I'm working on a PR to change the referenced github repo to the redcap-tools one. Is Scott Burns still the maintainer we want to list in setup.py?

**Comment by pwildenhain** [comment]
Good question -- I would list him as the creator, and list me as a maintainer.

Once your PR is merged, we can close this issue

**Comment by njvack** [comment]
I... I don't actually know your name! I'll drop the PR without it; that'll be a trivial lil change in setup.py later

**Comment by pwildenhain** [comment]
Haha, Paul Wildenhain 😉
