### ISSUE TITLE
Documentation website displaying wrong documentation version

### ISSUE THREAD

**Issue by jimklo** [redcap-tools/PyCap#217]
The website located at http://redcap-tools.github.io/PyCap/ displays a version number in the upper right corner as 1.1.3.  However, when browsing the documentation, I've noticed that it is actually displaying a version other than 1.1.3.

I've noticed this as the signature for v1.1.3 of [Project.import_metadata](https://github.com/redcap-tools/PyCap/blob/5a77a40564deb2b58e796e4fdac0c5c874dd2f0c/redcap/project.py#L601) differs from the [Project.import_metadata API documentation](http://redcap-tools.github.io/PyCap/api_reference/project/#redcap.project.Project.import_metadata).

Expected behavior is to see the documentation version match the implementation version.

**Comment by pwildenhain** [comment]
We're in the process of releasing 2.0 right now, hoping to release in the next few weeks.

The new documentation came with the new 2.0 version, but the last pypi version is 1.1.3, which is why they're out of sync right now. 

Once 2.0 is released, we should be good.

If you want to try out 2.0 and see if there are any issues (and be able to reference the API docs) then install the latest pre release with 

pip install PyCap --pre

**Comment by jimklo** [comment]
cursory look, it appears that there might be several breaking changes, and we're still using RC 10.x.  Plan to update to latest RC soon, will update pycap to 2.x at that time.

**Comment by pwildenhain** [comment]
Yup, checkout #216 for the full changelog. I don't think the breaking changes are too bad, but they are definitely there
