### ISSUE TITLE
Using filter_Logic - Insufficient documentation

### ISSUE THREAD

**Issue by rmcbarnettahrc** [redcap-tools/PyCap#221]
Hoping this is the right place to ask these questions, if not apologies and please direct me.🙏🏽

I'm trying to use filter_logic to find all the record ids that contain a suiffix... in this case "AL". 

I've tried two different ways: 

 df = project.export_records(format='df', fields=allfields, filter_logic= "where cr_record_id LIKE %AL%")

 df = project.export_records(format='df', fields=allfields, filter_logic= "AL in cr_record_id")

Didnt work. 

How do I use the filter_logic to just grab all the recordids that contain AL as a  substring?

**Comment by pwildenhain** [comment]
In general, these sorts of questions are better suited for your REDCap admins, since they are more about how REDCap itself works rather than how PyCap works. I can see how the lines get easily blurred though, so no worries at all, feel free to bring any questions here first if you want, I just may not be able to answer them

The REDCap API help docs are very useful for questions like this. Here is what I found by searching them:

> `filterLogic`
> String of logic text (e.g., [age] > 30) for filtering the data to be returned by this API method, in which the API will only return the records (or record-events, if a longitudinal project) where the logic evaluates as TRUE. This parameter is blank/null by default unless a value is supplied. Please note that if the filter logic contains any incorrect syntax, the API will respond with an error message. 

It seems like you're trying to using a sql syntax, when instead you need to use REDCap specific syntax (like what you might use in a calculated field or the branching logic of a form).

I think the `ends_with` special function is what you're looking for here:

![image](https://user-images.githubusercontent.com/35195136/160867652-663a97c7-7d5b-4877-aeb1-a9617d9cdc9d.png)

The documentation for the API methods can be found at: https://yourredcapurl.edu/api/help/?content=exp_records and 
the documentation on special functions can be found here: https://yourredcapurl.edu/redcap_v12.0.6/DataEntry/special_functions_explanation.php

You'll just need to replace `yourredcapurl` with whatever the REDCap url is for your site and `12.0.6` with whatever version of REDCap your site is on, which you should be able to find at the bottom of the REDCap home page 

If you think the `PyCap` documentation for `filter_logic` can be improved, please submit a PR with your proposed changes 👍🏻

**Comment by rmcbarnettahrc** [comment]
Appreciate this response so much! Thank you. Will take a look at ends with and also the red cap docs
