### ISSUE TITLE
Unexpected Behavior: invitation_send_time is blank from export_survey_participant_list method

### ISSUE THREAD

**Issue by chris-sutton** [redcap-tools/PyCap#240]
When I call the export_survey_participant_list method with either format_type 'df' or 'json' (haven't tried others) the invitation_send_time is blank, even for those with invitation_sent_status of 1. 
`events_json = project.export_survey_participant_list(instrument='survey1', event=events[10])`

`events_json` contains (I am only showing the parts that are needed):
```
invitation_sent_status': 0,
  'invitation_send_time': '',
  'response_status': 0,
```
and
```
'invitation_sent_status': 1,
  'invitation_send_time': '',
  'response_status': 2,
```

I expected the second example to have some sort of datetime, number, string but it comes out blank for all.

In REDCap the participant list and survey invitation log are separate tabs, and the time is only present in the log, not the participant list.  I assumed, based on the API documentation for REDCap and the playground options that the only part of the survey distribution tool that the API allowed was the participant list, so I was happy to see it might have a datetime available for us.  But it seems that it's always blank (or NaN when format_type='df').

**Comment by pwildenhain** [comment]
Interesting!


What happens when you do this in the API playground of your redcap instance? Does the JSON look different?

**Comment by chris-sutton** [comment]
Same output. The only way I get the send time is with the manual Download log in the tool.

**Comment by pwildenhain** [comment]
Got it. Unfortunately this means this is a REDCap API issue, rather than a `PyCap` issue.

Here are a couple of next steps you can take:

1. Check your version of REDCap -- if it's not the latest, see if upgrading to the latest version would solve your issue

2. If you have the latest version/ or the latest version wouldn't solve your issue, reach out to your REDCap administrator. They can reach out to the REDCap development team and let them know of this behavior. They will fix it for a future version of REDCap, which your administrator will need to install.

**Comment by chris-sutton** [comment]
I have contacted my REDCap administrators about it. I really appreciate your help and this package that has been very easy to use. I only know how to find our version of REDCap (12.5.8) but can't find the latest version for comparison. Which probably won't help me anyway since I'm not a REDCap developer for my institution. Where would I find latest version of REDCap?

**Comment by pwildenhain** [comment]
From a quick google search on what versions other institutions are using, that seems like the latest version

Glad you're enjoying the package!
