### ISSUE TITLE
Add option for import_records to not overwrite

### ISSUE THREAD

**Issue by JANHMS** [redcap-tools/PyCap#242]
### Summary
First of all thanks for building up this cool tool.
 
I was wondering, if it would be possible to add a possibility to the `import_records` method to actually not overwrite values, which are already within the REDCap instance. 
E.g. a person filled out the data already manually. Then I would not want to overwrite this data. With the current option `normal` it is overwriting this fields within REDCap.

**Comment by pwildenhain** [comment]
Interesting -- too be honest, I'm also not 100% percent sure what the `overwrite` parameter really does. I think if you set it to `overwrite` and then you only write back a subset of data for a record, it will **delete* the existing data in that record.

But like you pointed out, even with "normal" mode it doesn't seem to respect existing data in records.

Can I ask a little bit more about your use case?

If there is any existing data in a record, do you want to avoid writing to it altogether? 

Or do you want to go field by field, record by record, checking for the existence of data, and writing only to those fields for those records that don't have existing data?

**Comment by pwildenhain** [comment]
Got it.

To me this seems outside of the scope of what PyCap is for, which is a simple wrapper around the REDCap API

However, I do think this is a really interesting use-case, and interesting problem.

I think you'll need to go a custom route with this, and below is some (not fully tested ⚠️ ) code on how to solve this problem

```python
import os

import pandas as pd

from redcap import Project

my_project = Project("https://redcap.somewhere.edu/api/", os.getenv("MY_PROJECT_TOKEN"))
current_project_data = my_project.export_records(format="df)
# you might get this from somewhere else, but it's the data you're looking to import into your project
new_project_data = pd.read_csv("new_data_for_my_project.csv")

to_import = pd.DataFrame()
for idx, row in new_project_data.iterrows():
    try:
        current_record_data = current_project_data.loc[[idx]].copy()
    except KeyError:
        # This is a completely new record
        to_import = to_import.append(new_project_data.loc[[idx]])
        # no need to check column by column
        continue
    for col in current_record_data.columns:
        has_current_value = current_record_data[col].notna().values[0]
        if has_current_value:
            # Don't overwrite any pre-existing values. With overwrite="normal" a blank value will not replace an existing value
            current_record_data[[col]] = pd.NA
    
    to_import = to_import.append(current_record_data)


num_updated = my_project.import_records(to_import, import_format="df")
```

Couple of notes:
- `pandas` is not my strong suit, so the code above is almost certainly not optimized 🙈 
- The logic above will breakdown for checkbox fields, because rather than checking for `notna()` you'll need to check to see if all the values for a given checkbox column are all zero. You'll need to also export the project metadata to easily tell which fields are checkbox fields. I didn't go into that here, but you should be able to run with that if you need to.

Try this out, let me know what you think 😉 This could honestly be worth asking the REDCap team to give a new option for `overwrite` in `import_records` that's like `conservative` or something like that, where it doesn't overwrite _any_ existing data

**Comment by pwildenhain** [comment]
Let me know if this was helpful for you or not, curious to hear about the solution you landed on
