### ISSUE TITLE
REDCap now supports delete through API

### ISSUE THREAD

**Issue by damonms** [redcap-tools/PyCap#76]
Are there any plans to upgrade PyCap to include delete for records? If not, I will take a stab at it. It shouldn't take long. 

Cheers from Steve and the VUIIS folks

**Comment by sburns** [comment]
Hi Steve!

Currently no plans but I'd of course welcome a PR. I _think_ they finally revoked my vandy credentials from REDCap, so if you submit a PR it will likely fail CI :(

**Comment by damonms** [comment]
OK. I have a fix already working. I'll get a PR formulated and submit for approval.

Cheers,
Steve

________________________________

**Comment by remifrazierucsf** [comment]
Steve – keep us posted; I’ve been extending some classes as well and maybe we could merge.

**Comment by bobromeo** [comment]
The title of this issue is not yet OK :), the Pull Request is not yet handled.
Looked into files of the branch, 'delete_record' only deletes 1 record, so the README.rst should be changed to singular.
-OR-
Better still: the .py could be changed to allow multiple records to be deleted, because the API allows for records[0], records[1] etc.
I am a noob at GitHub and Python is not my forté, but here's my 3cts solution for deleting records.
This works, but i am not yet using records[1] etc, have to dig in a bit deeper :)
Also: a nice 'delete_record**s**' should iterate over chunks of 1000 or so ...
<pre>dataRep = {
    'token': api_key,
    'content': 'report',
    'format': 'csv',
    'report_id': '16',
    'rawOrLabel': 'raw',
    'rawOrLabelHeaders': 'raw',
    'exportCheckboxLabel': 'false',
    'returnFormat': 'csv'
}
dataDel = {
    'token': api_key,
    'action': 'delete',
    'content': 'record',
    'records[0]': 'xxx'
}
rr = requests.post(api_url, data = dataRep, verify=False)
for rrl in rr.iter_lines(chunk_size=128,decode_unicode=True):
    if(rrl != 'record_id'):
        dataDel["records[0]"] = rrl.strip('\"')
        rd = requests.post(api_url, data = dataDel, verify=False)
rr = requests.post(api_url, data = dataRep, verify=False)
print(rr.text)
</pre>

**Comment by pwildenhain** [comment]
See my comment in the PR for how to easily delete multiple records through the API: https://github.com/redcap-tools/PyCap/pull/77#issuecomment-575231391
**TL:DR** Change `records[0]` to `records[]` in the body of the POST request to pass a list of records to be deleted
