### ISSUE TITLE
redcap permissions

### ISSUE THREAD

**Issue by reductionist** [redcap-tools/PyCap#78]
Hi all, very sorry for posting this here, but I'm having a hard time finding a RedCAP forum accessible to end users.  My question is whether it's possible to grant and change permissions for a single person on multiple projects.  I have a couple hundred projects, and need to grant one person access to all of them.  Is there an easy way to do this, and if not, could it be scripted?

Thanks!

**Comment by remifrazierucsf** [comment]
If you are not a system admin for your REDCap instance this is going to be tough.  I’d suggest asking your institution’s sysad for help, as they should be able to make this change through the backend for you.  Otherwise I think you should be able to accomplish this with the superuser API key if you can get the admin to grant that access level to you.

Failing that, if you have the UID of all of your projects, you could almost certainly accomplish what you’re looking to do using some sort of web automation package.  If you’re not comfortable setting it up via code, I suspect you could hack together something to do it for you with the Selenium IDE in Firefox, which can be used as a pretty end-user-accessible automation tool.

Best of luck!

-Remi

___ _ ____ _ _____ _________ __ ______
Remi Frazier
remi.frazier@ucsf.edu<mailto:remi.frazier@ucsf.edu>
Data Scientist/Systems Architect
UCSF School of Medicine
550 16th Street, Suite 3153
San Francisco, CA 94143
415.502.1000 ext. 66270 (vm only) <-- new number

**Comment by reductionist** [comment]
Hi Remi, thanks so much for your help and quick response!  I'm actually the
person who needs to be granted the permissions (sorry for misleading
original post), and our main Redcap person with full admin rights doesn't
know how to do this.  I'm asking for him because I don't want him to spend
hours going through each project individually to grant me permissions.  So
assuming he does have full admin control, where should I point him that
might help him do this more quickly?

Thanks again!

Tyler

**Comment by pwildenhain** [comment]
🙏 Hope you got this resolved! Closing since it's off-topic
