### ISSUE TITLE
Export_records hash identifiers and date shift options

### ISSUE THREAD

**Issue by Mkang1204** [redcap-tools/PyCap#94]
Dear all, 

I was trying to export the records with hashed id and date shift using the pycap package, but I didn't find the right function to implement that as what I find in the REDCap API. may I know whether it is feasible through the package functions? Thank you!

![image](https://user-images.githubusercontent.com/28990623/53110850-868ae600-3501-11e9-8ec4-84eb045ceb06.png)

**Comment by sburns** [comment]
Hi @Mkang1204, thanks for the issue. I'm not aware of if that's possible through the API. It's certainly possible, but this may just be a feature available through the Export functionality in the web GUI. Are you able to view the API documentation on your redcap site?

**Comment by remifrazierucsf** [comment]
This is not a feature available through the REDCap API.  The only way I’m aware of to recover hased record_id and dateshifting from the REDCap “Export” feature is through the front-end.  API access grants access to the raw data in a project, which is why it should be so carefully guarded.

Sorry we don’t have better news, @mkang1204
___ _ ____ _ _____ _________ __ ______
Remi Frazier (he/him/his)
remi.frazier@ucsf.edu<mailto:remi.frazier@ucsf.edu>
Data Scientist/Systems Architect
UCSF Academic Research Systems
1855 Folsom Street
San Francisco, CA 94103
415.353.4800

**Comment by sburns** [comment]
Of course, given access to the raw data via PyCap, you can implement date-shifting and ID-hasing yourself and discard the (true) raw data before pushing it through other processes.

**Comment by remifrazierucsf** [comment]
Agreed with Scott.  Also, if the goal is to match data as it came out of a deidentified REDCap export you’ll need to dig directly into the source code for REDCap.

**Comment by Mkang1204** [comment]
Hi Scott and Remi,

Thanks a lot for your quick reply! My goal was to export records with de-identified patient info so that's why I asked about the functions in the package (you are right that the web API can do that but I am looking for a way to bulk export records and automate the process). Probably I'll need to contact REDCap team and see if they have solutions. Thanks again:)

**Comment by sburns** [comment]
What do you want to do w/ the exported data? If its a question of PHI handling, the data rests encrypted in redcap and is encrypted in-transit to wherever your script is running. As long as you don't write out the identifiable fields to disk and/or hash them before writing, then you should be ok.

Say your script is

```
#!/bin/env python

import datetime
import hashlib
import random


from pycap import Project
salt = "SOME RANDOM STRING"

project = Project(URL, TOKEN)

phi_records = project.export_records(format='df')

def obfuscate_id(record_id):
    """ This salts and hashes the incoming record id """
    return hashlib.sha1("{}{}".format(salt, record_id)).hexdigest()


def obfuscate_date(date_value):
    """ Obfuscates incoming date value by adding random amount of days to it """
    td = timedelta(days=random.randint())
    return date_value + td

phi_records['record_id'] = phi_records['record_id'].map(obfuscate_id)
phi_records['sensitive_date'] = phi_records['sensitive_date'].map(obfuscate_date)

phi_records.to_csv(....)
```

(This is pretty much guaranteed to be wrong somewhere but should give you an idea about how to proceed)

If you're looking to combine the hashed ID with other data sources then it gets a lot harder because REDCap is likely salting those values as well and they may be hesitant to give up their salt.

**Comment by Mkang1204** [comment]
Thanks for the suggestions, Scott! I was planning to the de-identified clinical data to merge with the genetic data and upload to Azure cloud for data analysis and easier collaboration for research. Now we are considering using our own encryption method instead of relying on redcap's. But still many thanks to your timely response!
